# Name - Mukul Jindal
# Group - 3CS10
# Roll No- 102116063

In [8]:
import numpy as np
from PIL import Image

# Q1

In [15]:
# Q1 A
arr = np.array([1,2,3,6,4,5])
reversedArr = np.flip(arr)
print("Orignial Arr: ",arr)
print("Reversed Arr: ",reversedArr)

#Q1 B
array1 = np.array([[1,2,3],[2,4,5],[1,2,3]])
flattenArray1 = np.ndarray.flatten(array1)
print("Method 1: ",flattenArray1)
flattenArray2 = np.ndarray.ravel(array1)
print("Method 2: ",flattenArray2)

# Q1 C
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1, 2], [3, 4]])
if np.array_equal(arr1,arr2):
    print("Equal")
else:
    print("Not equal")

print("arr1>arr2")
print(np.greater(arr1,arr2))
print("arr2>arr1")
print(np.greater(arr2,arr1))
print("arr1>=arr2")
print(np.greater_equal(arr1,arr2))
print("arr2>=arr1")
print(np.greater_equal(arr2,arr1))

# Q1 D
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3,])

values,index,counts = np.unique(x,return_index=True,return_counts=True)
print("Value: ",values[counts==counts.max()]," Index:", index[counts==counts.max()])

values,index,counts = np.unique(y,return_index=True,return_counts=True)
print("Value: ",values[counts==counts.max()]," Index:", index[counts==counts.max()])

# Q1 E
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Sum of all elements",np.sum(gfg))
print("Sum of  elements along column",np.sum(gfg,0))
print("Sum of elements along row\n",np.sum(gfg,1))

# Q1 F
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print("sum of diagonal elements: ",np.trace(n_array,))
values, vectors = np.linalg.eig(n_array)
print("Eigen values: ",values)
print("Eigen vectors: ",vectors)
print("Inverse: ",np.linalg.inv(n_array)) 
print("Determinant: ",np.linalg.det(n_array))

# Q1 G-i
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
multiplication = np.matmul(p,q)
print(multiplication)

# Q1 G-ii
p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
multiplication = np.matmul(p,q)
print(multiplication)

#Q1 H 
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print(np.inner(x,y))
print(np.outer(x,y,out=None))
print(np.cross(x,y))

Orignial Arr:  [1 2 3 6 4 5]
Reversed Arr:  [5 4 6 3 2 1]
Method 1:  [1 2 3 2 4 5 1 2 3]
Method 2:  [1 2 3 2 4 5 1 2 3]
Equal
arr1>arr2
[[False False]
 [False False]]
arr2>arr1
[[False False]
 [False False]]
arr1>=arr2
[[ True  True]
 [ True  True]]
arr2>=arr1
[[ True  True]
 [ True  True]]
Value:  [1]  Index: [0]
Value:  [1 3]  Index: [0 4]
Sum of all elements 45
Sum of  elements along column [[20  9 16]]
Sum of elements along row
 [[14]
 [16]
 [15]]
sum of diagonal elements:  176
Eigen values:  [98.16835147 28.097044   49.73460452]
Eigen vectors:  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:  [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant:  137180.0000000001
[[16 19]
 [26 31]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10

# Q2

In [14]:
array = np.array([[1, -2, 3],[-4, 5, -6]])

# Q2 A-i
print(array.__abs__())

# Q2 A-ii
print("25th percentile: ", np.percentile(array,25,axis=0))
print("50th percentile: ", np.percentile(array,50,axis=0))
print("75th percentile: ", np.percentile(array,75,axis=0))
print("25th percentile: ", np.percentile(array,25,axis=1))
print("50th percentile: ", np.percentile(array,50,axis=1))
print("75th percentile: ", np.percentile(array,75,axis=1))

# Q2 A-iii
print("Mean Colmun: ", np.mean(array,axis=0))
print("Median Colmun: ", np.median(array,axis=0))
print("Standard Deviation Colmun: ", np.std(array,axis=0))
print("Mean Row: ", np.mean(array,axis=1))
print("Median Row: ", np.median(array,axis=1))
print("Standard Deviation Row: ", np.std(array,axis=1))

# Q2 B
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print("Array :",a)
print("Floor Values :", np.floor(a))
print("Ceiling Values :",np.ceil(a))
print("Truncated Values :",np.trunc(a))
print("Rounded Values :",np.round(a))

[[1 2 3]
 [4 5 6]]
25th percentile:  [-2.75 -0.25 -3.75]
50th percentile:  [-1.5  1.5 -1.5]
75th percentile:  [-0.25  3.25  0.75]
25th percentile:  [-0.5 -5. ]
50th percentile:  [ 1. -4.]
75th percentile:  [2.  0.5]
Mean Colmun:  [-1.5  1.5 -1.5]
Median Colmun:  [-1.5  1.5 -1.5]
Standard Deviation Colmun:  [2.5 3.5 4.5]
Mean Row:  [ 0.66666667 -1.66666667]
Median Row:  [ 1. -4.]
Standard Deviation Row:  [2.05480467 4.78423336]
Array : [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]
Floor Values : [-2. -2. -1.  0.  1.  1.  3.]
Ceiling Values : [-1. -1. -0.  1.  2.  2.  3.]
Truncated Values : [-1. -1. -0.  0.  1.  1.  3.]
Rounded Values : [-2. -2. -0.  0.  2.  2.  3.]


# Q3 A

In [13]:
array = np.array([10, 52, 62, 16, 16, 54, 453]),
# i
sortedArray = np.sort(array)
print(sortedArray)
# ii
sortIndices = np.argsort(array)
print(sortIndices)
# iii
smallest4Elemets = np.partition(array,kth=4)[0][:4]
print(smallest4Elemets)
# iv
largest5Elements = np.partition(array,kth=-5)[0][-5:]
print(largest5Elements)


[[ 10  16  16  52  54  62 453]]
[[0 3 4 1 5 2 6]]
[16 10 16 52]
[ 16  52  62  54 453]


# Q3 B

In [17]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integersFiltered = array[array==array.astype(int)]
print(integersFiltered)
floatFiltered = array[array!=array.astype(int)]
print(floatFiltered)

[1. 2. 3. 2.]
[1.2 2.2]


# Q4

In [9]:
#A
def img_to_array(path):
    img = Image.open(path)
    img_array = np.array(img)

    if len(img_array.shape) == 3:
        r, g, b = img_array[:,:,0], img_array[:,:,1], img_array[:,:,2]
        np.savetxt('red_channel.txt', r, fmt='%d')
        np.savetxt('green_channel.txt', g, fmt='%d')
        np.savetxt('blue_channel.txt', b, fmt='%d')

    else:
        np.savetxt('gray_image.txt', img_array, fmt='%d')
    
    return img_array

image_path  = "../Machine Learning/img.jpg"
imgdata=img_to_array(image_path )
#B
print(imgdata)


[[[30 67 94]
  [26 63 90]
  [26 63 90]
  ...
  [28 65 92]
  [26 63 90]
  [22 59 86]]

 [[30 67 94]
  [27 64 91]
  [26 63 90]
  ...
  [22 59 86]
  [22 59 86]
  [21 58 85]]

 [[29 66 93]
  [26 63 90]
  [26 63 90]
  ...
  [21 58 85]
  [22 59 86]
  [24 61 88]]

 ...

 [[62 48 39]
  [63 49 40]
  [59 45 36]
  ...
  [35 30 24]
  [34 29 23]
  [34 29 25]]

 [[60 46 37]
  [60 46 37]
  [56 42 33]
  ...
  [36 31 25]
  [35 30 24]
  [34 29 25]]

 [[58 44 35]
  [58 44 35]
  [55 41 32]
  ...
  [36 31 25]
  [35 30 24]
  [33 28 24]]]
