# Q1

In [ ]:
import random 
import numpy as np
rows = 4
cols=4
matrix1 = np.random.randint(0,10,size=(rows,cols),dtype=int)
print("Matrix 1:\n",matrix1)
matrix2 = np.random.randint(0,10,size=(rows,cols),dtype=int)
print("Matrix 2:\n",matrix2)


In [ ]:
import sys

print("python version")
print(sys.version)

# Q2

In [19]:
test_list=[[5,8,10],[2,0,9],[5,4,2],[2,3,9]]
ans = {}
i=0
for array in test_list[1:]:
   ans.update({test_list[0][i] : array})
   i+=1
print(ans)   

{5: [2, 0, 9], 8: [5, 4, 2], 10: [2, 3, 9]}


# Q3

In [32]:
test_list1 = [1,4,4,8,5,5,6,7,4]
test_list1.sort()
ans=[]
i=0
while i != len(test_list1):
    similarElements=[]
    if i != len(test_list1)-1: 
        if(test_list1[i]==test_list1[i+1]):
            similarElements.append(test_list1[i])
            j=0
            while True:
                if(test_list1[i]==test_list1[i+1+j]):
                    similarElements.append(test_list1[i])
                    j=j+1
                else:
                    break
            i=i+j+1
            ans.append(similarElements)
        else:
            ans.append([test_list1[i]])  
            i=i+1
    else:
        ans.append([test_list1[i]])  
        i=i+1
print(ans)

[[1], [4, 4, 4], [5, 5], [6], [7], [8]]


# Q4

In [41]:
print("Matrix 1:\n",matrix1)
print("Matrix 2:\n",matrix2)
addition = matrix1 + matrix2
print("Addition:\n",addition)
subtraction = matrix1 - matrix2
print("Subtraction:\n",subtraction)

Matrix 1:
 [[2 9 9 4]
 [1 9 3 3]
 [7 0 0 7]
 [5 2 0 8]]
Matrix 2:
 [[6 3 9 1]
 [0 1 7 8]
 [9 4 8 1]
 [5 2 6 9]]
Addition:
 [[ 8 12 18  5]
 [ 1 10 10 11]
 [16  4  8  8]
 [10  4  6 17]]
Subtraction:
 [[-4  6  0  3]
 [ 1  8 -4 -5]
 [-2 -4 -8  6]
 [ 0  0 -6 -1]]


# Q5

In [39]:
def subMatrix(matrix,rows,cols):
    for i in range(rows):
        subMatrix=[]
        for j in range(i+1):
            subMatrix.append(matrix[j][:i+1])
        if((subMatrix[0][0]+subMatrix[i][i])%2 == 0):
            print(np.array(subMatrix))
subMatrix(matrix1,rows,cols)

[[2]]
[[2 9 9]
 [1 9 3]
 [7 0 0]]
[[2 9 9 4]
 [1 9 3 3]
 [7 0 0 7]
 [5 2 0 8]]


# Q6

In [34]:
print("Matrix:",matrix1)
row_sums = np.sum(matrix1, axis=1)
print(row_sums)

Matrix: [[2 9 9 4]
 [1 9 3 3]
 [7 0 0 7]
 [5 2 0 8]]
[24 16 14 15]
